// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsvMT5AlAJ0lVQFRJrLA2X1PZqUtgRUfQ',
    appId: '1:821885695604:web:0af844fef2ad14f7218321',
    messagingSenderId: '821885695604',
    projectId: 'aurex-blockchain-transactions',
    authDomain: 'aurex-blockchain-transactions.firebaseapp.com',
    storageBucket: 'aurex-blockchain-transactions.firebasestorage.app',
    measurementId: 'G-2231QKXBCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgUdDR0GUSw-X-vv96DsooxTulEh-uF_E',
    appId: '1:821885695604:android:a6675f78ddf1ffff218321',
    messagingSenderId: '821885695604',
    projectId: 'aurex-blockchain-transactions',
    storageBucket: 'aurex-blockchain-transactions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBGo7_-AI-m9M4hkZqC1LRvNRd-WZ924I',
    appId: '1:821885695604:ios:e3e38551a3c2cc54218321',
    messagingSenderId: '821885695604',
    projectId: 'aurex-blockchain-transactions',
    storageBucket: 'aurex-blockchain-transactions.firebasestorage.app',
    androidClientId: '821885695604-lddt3l45v557hl1g8pei43ocn24vsoj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.aurex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBGo7_-AI-m9M4hkZqC1LRvNRd-WZ924I',
    appId: '1:821885695604:ios:e3e38551a3c2cc54218321',
    messagingSenderId: '821885695604',
    projectId: 'aurex-blockchain-transactions',
    storageBucket: 'aurex-blockchain-transactions.firebasestorage.app',
    androidClientId: '821885695604-lddt3l45v557hl1g8pei43ocn24vsoj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.aurex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsvMT5AlAJ0lVQFRJrLA2X1PZqUtgRUfQ',
    appId: '1:821885695604:web:7b80a903b1136f1a218321',
    messagingSenderId: '821885695604',
    projectId: 'aurex-blockchain-transactions',
    authDomain: 'aurex-blockchain-transactions.firebaseapp.com',
    storageBucket: 'aurex-blockchain-transactions.firebasestorage.app',
    measurementId: 'G-ZGR5M79TB5',
  );
}
