[req]
default_bits       = 2048
distinguished_name = req_distinguished_name
req_extensions     = req_ext
prompt             = no

[req_distinguished_name]
C  = IL
ST = Israel
L  = Herzeliya
O  = CyberClass
CN = MySecureServer

[req_ext]
subjectAltName = @alt_names

[alt_names]
IP.1 = 10.100.102.58
DNS.1 = nadav.cohen
DNS.2 = localhost